# Generated by Django 3.0.3 on 2020-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
